# config.toml

baseurl = "http://rasp164"
languageCode = "nl"
title = "mijn aantekeningen . . . "
copyright = "(c) 2016, dirk postma."
enableRobotsTXT = "true"

theme = "hyde-y"

# Pagination
paginate = 25
paginatePath = "page"

# disqus 
disqusShortname = "www-dirkpostma-com"

[permalinks]
    post = "/:year/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"
    updated = "updated"

[author]
    name = "dirk"
#   email = "yourname@example.com"


[params]
# You can use markdown here.
    Author = "Dirk Postma"
    brand = "dirk postma"
    topline = "Mijn aantekeningen over computers etc, zodat ik het niet nog een keer hoef uit te zoeken. Site is in aanbouw"
    # footline = "code with <i class='fa fa-heart'></i>"

    # google analytics tracking id
    googleAnalytics = "UA-20451652-4"


# Sidebar position
# nadat ik deze had aangezet verdween de kop boven de site
# false, true, "left", "right"
    sidebar = "left"

# Text for the top menu link, which goes the root URL for the site.
# Default (if omitted) is "Home".
    home = "Home"

# Select a syntax highight.
# Check the static/css/highlight directory for options.
     highlight = "default"

# Sidebar social links.
    github = "dirk2011" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = true
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

#eof

